### ISSUE TITLE
RFE: Ability to use met to count entities by registrationAuthority, by type

### ISSUE THREAD

**Issue by canariecaf** [GEANT/met#10]
Many federations now have eduGAIN in their aggregate and when met reports on entities in a federation, it's not their native federation and doesn't provide a clear view of which entities are locally registered.  

I would propose that on the federations summary page list 'total local entities', local SPs, local IdPs to indicate entities that originate with that federation.

I believe this would be helpful to many to understand just which entities are local and which are not.

Additionally, if possible, if there was a way to click the actual results number and then filter the results for those entity types, it would be helpful too (e.g. click the hyperlinked number of SPs locally registered which will list just those SPs that are locally registered.)

**Comment by martinhaase** [comment]
How many federations are affected of this? Because there is also the model for federations to have two sets of metadata: the local ones, and a separate feed with re-signed eduGAIN metadata, excluding the local ones.

**Comment by nicoleharris** [comment]
I'm not convinced as to why MET should show the local feed - can you give a use case? At the moment we simply chose the aggregate that a federation considers its "main" feed.  The approaches taken by federations at the moment to metadata feeds are so diverse (https://wiki.edugain.org/index.php?title=Upstream-Downstream) that it would be impossible to capture cleanly

**Comment by martinhaase** [comment]
The use case is simple - there are DFN-AAI's two "main" feeds (depending on the LoA), and there is the re-signed eduGAIN metadata feed. As a user, I do not expect to see providers not registered there when browsing DFN-AAI. And similarly for other national federations. Otherwise, what would be the distinction between MET-browsing a national feed, and the eduGAIN feed?

**Comment by nicoleharris** [comment]
Users have no concept of edugain - they just want to know what is in a federation and don't care if it is "local" or not.  Ideally we want the feed which shows the maximum amount of entities that is available to the typical user in any federation.  Browsing a local fed + edugain doesn't help a user as they do not know if the federation is publishing all edugain entities back

**Comment by nicoleharris** [comment]
One solution proposed has been to filter on RA - and also consider anything that does not have RA as "local".  There are however complexities in implementing this and it seems that only federation operators are concerned with viewing local vs aggregated.
