### ISSUE TITLE
Entity categories incorrectly assigned - from Nick Roy

### ISSUE THREAD

**Issue by nicoleharris** [GEANT/met#18]
I think there may be a bug in MET, when I look at the entity with
entityID: http://wopac.cobiss.net/shibboleth in MET at:
https://met.refeds.org/met/entity/http%253A%252F%252Fwopac.cobiss.net%252Fshibboleth/

I see the http://id.incommon.org/category/registered-by-incommon entity
category, but that entity does not carry that category in metadata, in
eduGAIN, ArnesAAI or InCommon.

**Comment by biancini** [comment]
There was an error in the update of the DB information, so entities kept the categories even when they were removed.
Now it should be fixed, for the "http://wopac.cobiss.net/shibboleth" entity, in fact, I don't see any category now.
