### ISSUE TITLE
email addresses get presented as a link, but the link is messed up

### ISSUE THREAD

**Issue by surfnet-niels** [GEANT/met#19]
See e.g. https://met.refeds.org/met/entity/https%253A%252F%252Fwww.rediris.es%252Fsir%252Fuc3midp/

Where the link to the technical contact is being presented as:
https://met.refeds.org/met/entity/https%253A%252F%252Fwww.rediris.es%252Fsir%252Fuc3midp/sir@rediris.es

**Comment by biancini** [comment]
The problem were with metadata non compliant with specification.
The OASIS specification here: https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf, in fatct, describes the <EmailAddress> for contacts to be "Zero or more elements containing mailto: URIs representing e-mail addresses belonging to the contact person".
The referred metadata, instead, did not contain the mailto specification.

Given this is quite a frequent problem in our metadata, the met code was fixed to add mailto if not present.
