### ISSUE TITLE
Management of items not belonging to any federation

### ISSUE THREAD

**Issue by simie7** [GEANT/met#21]
On met.refeds.org there are some items, previously excluded from Litnet Fedi federation (search filter '.lt/'). I have admin rights on Litnet Fedi on this page, but have no rights to remove these items:

  https://survey.litnet.lt/simplesaml/module.php/saml/sp/metadata.php/default-sp
  https://sso.asu.lt/saml2/idp/metadata.php
  https://login.test.litnet.lt/simplesaml/saml2/idp/metadata.php

**Comment by biancini** [comment]
Patched update script to remove orphan entities (entities with no federation associated).
The three entities are now disappeared.
