### ISSUE TITLE
Show SSL certificate information

### ISSUE THREAD

**Issue by markwallsgrove** [GEANT/met#22]
Show the SSL certificate information related to the SP/IDP, mainly the hash used within the signature (related to [google breaking SHA-1](https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html)).

**Comment by markwallsgrove** [comment]
One could start from this [code](https://gist.github.com/markwallsgrove/94169332da50592e3f4a8e2195b07d01)

**Comment by biancini** [comment]
The implementation is  still quite poor, but the relevant information are now shown.
All information will be visible tomorrow (after the nightly data update).

In the federation view there is a summary showing certificate information: e.g.

```
Certificates statistics:
sha256: 76 | sha512: 3 | md5: 1 | sha1: 164
```

Same information is provided on each entity in the entity view page: e.g.

```
Certificates statistics:	sha256: 2
```

We could improve visualization, but I preferred to implement it quickly and eventually refine it in the future.

**Comment by markwallsgrove** [comment]
wohaa, nice work :+1:

**Comment by markwallsgrove** [comment]
Is there a branch related to this work?

**Comment by markwallsgrove** [comment]
https://github.com/GEANT/met/commit/22db489af61126a03905370be5801b409dd83ef8 seems to be the commit
