### ISSUE TITLE
export barf

### ISSUE THREAD

**Issue by alanbuxey** [GEANT/met#24]
hi,

when trying to export results as JSON or CSV, get error 500 with 'oops somethings gone wrong' text
(XML fine from tests so far done)

alan

**Comment by biancini** [comment]
Hi Alan,
can you help me reproduce the error?
Maybe it's some special character in your entity list or something like that, because in other situations export in JSON and CSV seem to work property.

How can I reproduce the error?

**Comment by alanbuxey** [comment]
thanks for getting back to me so quickly.

okay, on the meta data discovery tool, just use the search function, search
ANYTHING valid (that gets results, e.g. 'drupal' or 'journal') , then try
to export as JSON or CSV to get the error.

cheers

alan

**Comment by biancini** [comment]
Luckily it was a stupid bug, so easy to resolve.
Now anything seems to be working to me.
(apart from the problem with HTTPS certificate, which is being already managed).

**Comment by alanbuxey** [comment]
I was about to contact you about that - expired today just as i was on the
site! ;-)
