### ISSUE TITLE
SIRTFI, search by entity category

### ISSUE THREAD

**Issue by saltybeagle** [GEANT/met#27]
Where for art thou SIRTFI? `https://refeds.org/sirtfi` doesn't appear in the entities search form https://met.refeds.org/met/search_entities/

**Comment by biancini** [comment]
Hi, is SIRTFI an entity in a federation? Does it act as an IdP, SP or AA?
And which federation is it registered in (can't find it in eduGAIN)?

**Comment by saltybeagle** [comment]
SIRTFI is an assurance certification entity applied to IdPs or SPs. More info here: https://refeds.org/sirtfi

Here's an excerpt from metadata here: https://met.refeds.org/met/entity/https%253A%252F%252Fshib.unl.edu%252Fidp%252Fshibboleth/

```xml
<saml:Attribute Name="urn:oasis:names:tc:SAML:attribute:assurance-certification" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
<saml:AttributeValue>https://refeds.org/sirtfi</saml:AttributeValue>
</saml:Attribute>
```

**Comment by biancini** [comment]
Clara, but met lists entities (idp, sp or sa) browsing federations' metadata.
I think this is not an entity in this respect, and it is not an entity in any federation metadata file. Here the explaination why you don't find it in met.
Sounds reasonable?

**Comment by nicoleharris** [comment]
Hi Andrea

I think this is a feature request to add filtering on this tag to MET alongside: https://met.refeds.org/met/search_entities/.

Is that possible?

Thanks

Nicole

**Comment by biancini** [comment]
Met shows entities starting from federations' metadata filem
So if this is not in any federation file, the request is not implementable.
If entities as such must be added se could evaluate (a probably non so easy) extension to met, but in case I think some more specification about where to source information for these entities is needed...

**Comment by biancini** [comment]
Misunderstood the request at first instance.
Evaluating pull request from Brett Bieber to se if it solves the problem.

**Comment by biancini** [comment]
The patch seems to have worked!
Now in search, within entity categories, users can also choose sirfi.
