### ISSUE TITLE
SAFIRE metadata source

### ISSUE THREAD

**Issue by ghalse** [GEANT/met#29]
It's not clear where the right place to report this is.

MET seems to be fetching SAFIRE data from an out-of-date URL that predates our architecture transition (https://discservice.sanren.ac.za/safire.xml).

The definitive sources of metadata for SAFIRE are now https://metadata.safire.ac.za/. There are various feeds available there, including what we feed into eduGAIN, etc.

Perhaps the most useful source of data for MET is the hub's own operational feed. This is hidden from the directory listing above, and it's also technically "unsupported" because it is intended for internal use. However, it gives a complete picture of what's available to our participants. I'm happy to supply a URL out-of-band.

**Comment by biancini** [comment]
Thanks for having opened this issue!
I've upadted SAFIRE to download metadata from both these URLS:
- https://metadata.safire.ac.za/safire-prod-idp.xml
- https://metadata.safire.ac.za/safire-prod-sp.xml
Is it correct? In case, this means we would not need the URL you were talking about. It, instead, it is necessary to use it, please send it to me at my email address (andrea.biancini@reti.it).

**Comment by biancini** [comment]
Updated the metadata source as by private email.
Soon the new stats will be available in met.
Thanks,
