### ISSUE TITLE
SWAMID metadata not updating 

### ISSUE THREAD

**Issue by nicoleharris** [GEANT/met#30]
SWAMID metadata not updating  and has not updated since March 18, 2016

**Comment by biancini** [comment]
The version of PyFF library I am using within MET (which is the last one updating from pip) was failing validating the SWAMID metadata file with this error:

File "src/lxml/lxml.etree.pyx", line 3491, in lxml.etree._Validator.assertValid (src/lxml/lxml.etree.c:194796)
DocumentInvalid: Element '{urn:oasis:names:tc:SAML:2.0:assertion}AttributeValue', attribute '{http://www.w3.org/2001/XMLSchema-instance}type': The QName value 'xs:string' has no corresponding namespace declaration in scope.

I forced the validation of the file and now metadata gets updated.
