### ISSUE TITLE
Ghost Entries

### ISSUE THREAD

**Issue by nicoleharris** [GEANT/met#32]
Hello REFEDS,

Could someone please dump the hundreds of ghost entries no longer published by any federation that originated from ca.za?

You can easily find them with this query:
  https://met.refeds.org/met/search_service/?entityid=proxy.safire.ac.za

Many thanks,
Thomas Lenggenhager

**Comment by biancini** [comment]
There was an error in the update script caused as a regression to a modification of some time ago.
Now entities not registered in any federation should be dumped.
A.
