### ISSUE TITLE
Login to MET ends with error 500 on ACS

### ISSUE THREAD

**Issue by thijskh** [GEANT/met#33]
I logged in at `di 25 jul 2017  9:07:17 CEST` with `https://idp.surfnet.nl` and ended up with a "Error 500 Something goes wrong" on `https://met.refeds.org/saml2/acs/`. I'm also (understandably) not actually logged in after that.

**Comment by biancini** [comment]
Strange behaviour, I've noticed a very high clock skew that was preventing me to reach my IdP.
Now fixed, I managed to login successfully.
Can you retry and confirm the problem is still there?

**Comment by thijskh** [comment]
It works now, thanks!
