### ISSUE TITLE
Nit: the About MET page

### ISSUE THREAD

**Issue by hlflanagan** [GEANT/met#35]
Purely a nit, so treat accordingly
OLD:
"Metadata explorer tool is a fast way to find federations, entities and his relations through entity/federation metadata file information."

PROPOSED:
"Metadata explorer tool is a fast way to find federations, entities, and their relations through entity/federation metadata file information."

https://met.refeds.org/about/

**Comment by biancini** [comment]
Thansk for signalling this!
The grammar has been fixed! :-)
