### ISSUE TITLE
Entity Category not appearing in default view

### ISSUE THREAD

**Issue by nckroy** [GEANT/met#36]
Take a look at the following IdP:

https://met.refeds.org/met/entity/urn%253Amace%253Aincommon%253Acarleton.edu/

In all federations in which this exists, it has the REFEDS R&S entity category, but the default view of this IdP in MET does not show this category.

**Comment by biancini** [comment]
Thanks for the issue signaled!
The problem has been fixed. Now, if not differently specified, entities will show data from the first federation they're listed to.
Actually this is a better behaviour in general, in fact entities are included in met only when they're retrieved from one or more federations. So the "entity" page should always show data coming from one federation or another.
