### ISSUE TITLE
XML Export Fails

### ISSUE THREAD

**Issue by joshboon** [GEANT/met#39]
Exporting XML fails with a HTTP 500 for InCommon exports
https://met.refeds.org/met/entity/https%3A%2F%2Flogin.ithaca.edu%2Fidp%2Fshibboleth/?federation=incommon-federation&format=xml

**Comment by biancini** [comment]
I should have fixed the problem.
Now the download works as by attached file,
[entities_search_result.zip](https://github.com/GEANT/met/files/2270234/entities_search_result.zip)

**Comment by joshboon** [comment]
Looks great, thanks!
