### ISSUE TITLE
xml:lang not honoured correctly

### ISSUE THREAD

**Issue by ghalse** [GEANT/met#40]
In the entity properties, there is a drop down to select the language. This correctly changes the displayed language for the display name and description field but does not appear to affect the display of either the organisation name or the organisation display name.

These two fields don't necessarily display in English either. Given an entity that has an organisation display name in three languages (en, af, xh), it is selecting af. This is neither the first nor the last one in the underlying XML, leading me to assume it's sorting it alphabetically and displaying Afrikaans.

You can see this behaviour on:

https://proxy.safire.ac.za/birk.php/srvslsfed001.uct.ac.za/simplesaml/saml2/idp/metadata.php
https://proxy.safire.ac.za/birk.php/login.ru.ac.za/idp/shibboleth

The XML (as shown in the view XML link, as well as in the original source) for the latter is currently:

```
<md:OrganizationName xml:lang="en">Rhodes University</md:OrganizationName>
<md:OrganizationName xml:lang="af">Rhodes-universiteit</md:OrganizationName>
<md:OrganizationName xml:lang="xh">IYunivesiti iRhodes</md:OrganizationName>
```

and the display is:

![image](https://user-images.githubusercontent.com/7996633/46073712-faf56f00-c185-11e8-80fb-911711d42bb6.png)

**Comment by biancini** [comment]
Found the bug and fixed.
