### ISSUE TITLE
ArnesAAI Federation in not from Serbia, but Slovenia

### ISSUE THREAD

**Issue by urost** [GEANT/met#9]
Like the title says, I would argue that [ArnesAAI](https://met.refeds.org/met/federation/arnesaai-federation/) federation is from Slovenia, not Serbia. Not sure if [here](https://github.com/GEANT/met) is the right place to open this issue, though... ( I couldn't find an admin on [met refeds ](https://met.refeds.org/) site )

Cheers,
Uros

**Comment by nicoleharris** [comment]
Sorry Uros, that is now fixed for you!
